# Generated by Django 5.0.6 on 2024-06-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('total_population', models.IntegerField()),
                ('population_0_4', models.FloatField()),
                ('population_5_17', models.FloatField()),
                ('population_18_24', models.FloatField()),
                ('population_25_44', models.FloatField()),
                ('population_45_64', models.FloatField()),
                ('population_65_plus', models.FloatField()),
                ('population_under_18', models.FloatField()),
                ('population_18_54', models.FloatField()),
                ('population_55_plus', models.FloatField()),
                ('male_population', models.FloatField()),
                ('female_population', models.FloatField()),
            ],
        ),
    ]
