# Generated by Django 5.0.6 on 2024-07-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us_election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('republican', models.FloatField()),
                ('democratic', models.FloatField()),
                ('others', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
